name: Deploy CloudTalk

on:
  push:
    branches: [ main ] # Jalankan setiap ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/CloudTalk
            git pull origin main
            npm install
            npm run build
            pm2 restart cloudtalk || pm2 start npm --name "cloudtalk" -- start -- -p 3002